### ISSUE TITLE
Issues / review

### ISSUE THREAD

**Issue by ThaDafinser** [ThaDafinser/SpeedLoader#2]
Before creating the first release, some reals world application tests would be awesome.

Current problems:
- [ ] doctrine annotations are currently not possible (problem with autoload) https://github.com/ThaDafinser/SpeedLoader/blob/master/src/BuildClass.php#L244-L261
- [ ] traits are excluded, but could be cached https://github.com/symfony/symfony/blob/d0d7ae24e4d8ec27ff6992fd51d7d090424942be/src/Symfony/Component/ClassLoader/ClassCollectionLoader.php#L286-L294

Get some feedback from @Ocramius or @EvanDotPro

**Comment by Ocramius** [comment]
I would use this if it was based on https://github.com/nikic/PHP-Parser ;-)
